# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  calc-variables:
    if: ${{ github.ref_type=='tag' || github.ref_name=='main' }}
    uses: ./.github/workflows/_calc-variables.yml

  # This workflow contains a single job called "build"
  qodana:
    if: ${{ github.ref_type=='tag' || github.ref_name=='main' }}
    uses: ./.github/workflows/_code_quality.yml
    secrets: inherit

  build:
    if: ${{ github.ref_type=='tag' || github.ref_name=='main' }}
    needs: [calc-variables]
    uses: ./.github/workflows/_build-qwik.yml
    secrets: inherit
    with:
      version: ${{ needs.calc-variables.outputs.package-version }}

  deploy:
    if: ${{ github.ref_type=='tag' || github.ref_name=='main' }}
    needs: [build]
    uses: ./.github/workflows/_deploy.yml
    secrets: inherit

  create-release:
    if: ${{ github.ref_type=='tag' || github.ref_name=='main' }}
    needs: [calc-variables, qodana, build, deploy]
    uses: ./.github/workflows/_create-release.yml
    with:
      tag-name: ${{ github.tag_name || needs.calc-variables.outputs.version }}
      version: ${{ needs.calc-variables.outputs.version }}
